# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'

                charset: UTF8

                logging: '%doctrine.debug%'
                profiling: '%doctrine.debug%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'

        default_entity_manager: default
        entity_managers:
            default:
                connection: default

                metadata_cache_driver:
                    type: service
                    id: doctrine.metadata_cache
                query_cache_driver:
                    type: service
                    id: doctrine.query_cache
                result_cache_driver:
                    type: service
                    id: doctrine.result_cache

                class_metadata_factory_name:  Doctrine\ORM\Mapping\ClassMetadataFactory
                default_repository_class: Doctrine\ORM\EntityRepository
                naming_strategy: doctrine.orm.naming_strategy.underscore
 #               auto_mapping: false

#                mappings:
#                    default:
#                        mapping: true
#                        type: yml
#                        dir: '%kernel.root_dir%/config/doctrine/'
#                        prefix: App
#                        is_bundle: false