# Monolog Configuration
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      grouped
            excluded_404s:
                - ^/

        grouped:
            type: group
            members:
                - app

        app:
            type:  stream
            path:  '%kernel.logs_dir%/app.log'
            level: debug
