#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: debug # critical
            handler:      grouped
            excluded_404s:
                - ^/

        grouped:
            type:    group
            members:
                - app

        app:
            type:  stream
            path:  '%kernel.logs_dir%/app.log'
            level: debug

        console:
            type:   console
            channels: [!event, !doctrine]