# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    test:
        class: App\Controller\DemoController
        arguments:
            - '%env(DATABASE_HOST)%'
